# Generated by Django 4.1 on 2022-08-08 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatwedoinfo",
            name="service",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="whatwedo",
                to="services.service",
            ),
        ),
        migrations.AlterField(
            model_name="whatwedoolunits",
            name="info_block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="ol",
                to="services.service",
            ),
        ),
        migrations.AlterField(
            model_name="whatwedoulunits",
            name="info_block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="li",
                to="services.service",
            ),
        ),
    ]
