# Generated by Django 4.1 on 2022-08-08 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_whatwedoinfo_service_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tabssectioninfo",
            name="text",
        ),
        migrations.AddField(
            model_name="tabssectioninfo",
            name="col_1",
            field=models.CharField(
                default="", max_length=350, verbose_name="Колонка 1"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tabssectioninfo",
            name="col_2",
            field=models.CharField(
                default=" ", max_length=350, verbose_name="Колонка 2"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tabssectioninfo",
            name="col_3",
            field=models.CharField(
                default="", max_length=350, verbose_name="Колонка 3"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tabssectioninfo",
            name="col_4",
            field=models.CharField(
                default="", max_length=350, verbose_name="Колонка 4"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="howserviceworksinfo",
            name="service",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="how_it_works",
                to="services.service",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="services",
                to="services.servicecategory",
            ),
        ),
        migrations.AlterField(
            model_name="serviceimportantinfo",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="important",
                to="services.service",
            ),
        ),
        migrations.AlterField(
            model_name="tabssectioninfo",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tabs",
                to="services.service",
            ),
        ),
        migrations.AlterField(
            model_name="whatwedoinfo",
            name="service",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whatwedo",
                to="services.service",
            ),
        ),
        migrations.AlterField(
            model_name="whatwedoolunits",
            name="info_block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ol",
                to="services.service",
            ),
        ),
        migrations.AlterField(
            model_name="whatwedoulunits",
            name="info_block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="li",
                to="services.service",
            ),
        ),
    ]
