# Generated by Django 4.1 on 2022-08-08 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_remove_tabssectioninfo_text_tabssectioninfo_col_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatwedoulunits",
            name="info_block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ul",
                to="services.service",
            ),
        ),
    ]
