# Generated by Django 4.1 on 2022-08-09 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("callrequest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallRequestComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
                (
                    "call_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="callrequest.callrequest",
                    ),
                ),
            ],
        ),
    ]
