# Generated by Django 4.1 on 2022-08-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("callrequest", "0002_callrequestcomment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="callrequest",
            name="call_page",
        ),
    ]
