# Generated by Django 4.1 on 2022-08-10 09:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("preferences", "0003_alter_preferences_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyPreferences",
            fields=[
                (
                    "preferences_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="preferences.preferences",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="E-Mail: "),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=16, verbose_name="Номер телефона"),
                ),
                (
                    "contact_address",
                    models.CharField(max_length=200, verbose_name="Адресс офиса"),
                ),
                ("social_linkedin", models.URLField(verbose_name="LinkedIn")),
                ("social_tg", models.URLField(verbose_name="Telegram")),
                ("social_fb", models.URLField(verbose_name="Facebook")),
                ("social_behance", models.URLField(verbose_name="Behance")),
                ("social_vk", models.URLField(verbose_name="VK")),
                ("social_skype", models.URLField(verbose_name="Skype")),
                ("social_ig", models.URLField(verbose_name="Инстаграм")),
                ("about_company", models.TextField(verbose_name="О компании")),
                (
                    "seo_block_title",
                    models.CharField(max_length=100, verbose_name="Заголовок"),
                ),
                ("seo_block_text", models.TextField(verbose_name="Текст")),
                (
                    "seo_block_image",
                    models.ImageField(
                        upload_to="main/index/seo/", verbose_name="Изображение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки",
                "verbose_name_plural": "Настройки",
            },
            bases=("preferences.preferences",),
            managers=[
                ("singleton", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="OurClients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название компании клиента"
                    ),
                ),
                ("descr", models.TextField(verbose_name="Описание")),
                (
                    "rating",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="Оценка (1-5)",
                    ),
                ),
                (
                    "preferences",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="main.mypreferences",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Секция "Наши клиенты"',
                "verbose_name_plural": 'Секции "Наши клиенты"',
            },
        ),
        migrations.CreateModel(
            name="MainPageImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        upload_to="main/index/main/",
                        verbose_name="Изображение на главной странице",
                    ),
                ),
                (
                    "preferences",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_images",
                        to="main.mypreferences",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение для главной страницы",
                "verbose_name_plural": "Изображения для главной страницы",
            },
        ),
        migrations.CreateModel(
            name="LoansForAnyPurposeService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Заголовок")),
                (
                    "image",
                    models.ImageField(
                        upload_to="main/index/loans/", verbose_name="Изображение"
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "preferences",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_purpose",
                        to="main.mypreferences",
                    ),
                ),
            ],
            options={
                "verbose_name": 'Секция "Кредиты на любые цели"',
                "verbose_name_plural": 'Секции "Кредиты на любые цели"',
            },
        ),
    ]
