# Generated by Django 4.1 on 2022-08-09 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликовано"),
                ),
                (
                    "publish_date",
                    models.DateTimeField(blank=True, verbose_name="Дата публикации"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("descr", models.CharField(max_length=200, verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        upload_to="main/news/news-images/", verbose_name="Изображение"
                    ),
                ),
                (
                    "introduction",
                    models.TextField(blank=True, verbose_name="Вступительная часть"),
                ),
                ("conclusion", models.TextField(blank=True, verbose_name="Заключение")),
                ("slug", models.SlugField(verbose_name="slug")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewsSubtitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(max_length=250, verbose_name="Подзаголовок"),
                ),
                (
                    "text",
                    models.TextField(verbose_name="Текст подзаголовка(в html формате)"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtitles",
                        to="news.newsarticle",
                    ),
                ),
            ],
        ),
    ]
