# Generated by Django 4.1 on 2022-08-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="descr",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="publish_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата публикации"
            ),
        ),
    ]
